#!/usr/bin/with-contenv bash
#
# @see https://linux.die.net/man/1/inotifywait
#

if [ -n "$SKIP_APP" ]; then
  exit 0
fi

while inotifywait -e modify -qq /data/$FILE; do
  /app/main.js -f /data/$FILE -d /config/certs $ARGS
done
if [ ! -f "/data/$FILE" ]; then
  sleep 60
fi
